/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author MUHAMMAD ISHANUDDIN
 */
public class Pesanan extends javax.swing.JFrame {
    private String tot;
    public Statement st, sp;
    public ResultSet rs, rp;
    String sql;
    int hasil;
    String vpaket;
    /**
     * Creates new form Pesanan
     */
    
    Connection cn = koneksi.KoneksiDatabase.BukaKoneksi();
    public Pesanan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        paket = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        telepon = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        berat = new javax.swing.JTextField();
        total = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Total");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(720, 380, 170, 80);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Username");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(180, 190, 190, 80);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Alamat");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(180, 280, 190, 80);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Telepon");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(180, 380, 190, 80);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Pilih Paket ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(720, 180, 190, 80);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Kg");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(960, 270, 190, 80);

        paket.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        paket.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cuci+Setrika Reguler", "Cuci+Setrika Express", "Cuci+Setrika Full Express" }));
        paket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paketActionPerformed(evt);
            }
        });
        getContentPane().add(paket);
        paket.setBounds(890, 190, 260, 60);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Berat");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(720, 270, 150, 80);

        telepon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        telepon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teleponActionPerformed(evt);
            }
        });
        getContentPane().add(telepon);
        telepon.setBounds(330, 400, 270, 40);

        nama.setEditable(false);
        nama.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        getContentPane().add(nama);
        nama.setBounds(330, 210, 270, 40);

        alamat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamatActionPerformed(evt);
            }
        });
        getContentPane().add(alamat);
        alamat.setBounds(330, 300, 270, 40);

        berat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        berat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beratActionPerformed(evt);
            }
        });
        getContentPane().add(berat);
        berat.setBounds(890, 292, 60, 40);

        total.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(total);
        total.setBounds(890, 390, 80, 40);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel9.setText("BUAT PESANAN ANDA");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(490, 50, 460, 80);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setText("PESAN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(600, 500, 240, 80);

        jLabel2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel2AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(250, 30, 110, 70);

        setSize(new java.awt.Dimension(1382, 807));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void teleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teleponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teleponActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamatActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String vnama = String.valueOf(nama.getText());
        String valamat = String.valueOf(alamat.getText());
        String vberat = String.valueOf(berat.getText());
        String vtelepon = String.valueOf(telepon.getText());
        String vtotal = String.valueOf(total.getText());
        System.out.println("vtotal" +vtotal);

        try {
            
            String sql = "INSERT INTO customer (nama, alamat, telepon, paket, berat, total, status) VALUES ('" + vnama + "', '" + valamat + "', '" + vtelepon + "', '" + vpaket + "', '" + vberat + "', '" + vtotal + "', 'Sedang_Proses_Pengerjaan')";
            Statement s = cn.createStatement();
            s.executeUpdate(sql);
            JOptionPane.showMessageDialog(null,"Pesanan berhasil ditambahkan");
            dispose();
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void beratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beratActionPerformed
        // TODO add your handling code here:
        Object selectedValue = paket.getSelectedItem();
        if (selectedValue != null) {
            vpaket = selectedValue.toString();
            System.out.println("Selected value: " + vpaket);
        } else {
            System.out.println("No value selected");
        }
        String temp = berat.getText();
        try {
            int tempInt = Integer.parseInt(temp);
            if (selectedValue != null) {
                String value = selectedValue.toString();
                System.out.println("Selected value: " + value);
            }
            if (selectedValue == "Cuci+Setrika Reguler") {
                hasil = tempInt * 7500;
                String tot = Integer.toString(hasil);
                total.setText(tot);
            }
            if (selectedValue == "Cuci+Setrika Express") {
                hasil = tempInt * 14000;
                String tot = Integer.toString(hasil);
                total.setText(tot);
            }
            if (selectedValue == "Cuci+Setrika Full Express") {
                hasil = tempInt * 20000;
                String tot = Integer.toString(hasil);
                total.setText(tot);
            } else {
                System.out.println("No value selected");
            }
        } catch (Exception e) {
            System.out.println("error");
        }

    }//GEN-LAST:event_beratActionPerformed

    private void paketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paketActionPerformed

    private void jLabel2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel2AncestorAdded
        // TODO add your handling code here:
        jLabel2.setVisible(true);
        
    }//GEN-LAST:event_jLabel2AncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pesanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JTextField berat;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JTextField nama;
    private javax.swing.JComboBox<String> paket;
    private javax.swing.JTextField telepon;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
